changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feat
    - title: Bug Fixes
      labels:
        - fix
    - title: Performance
      labels:
        - perf
    - title: Documentation
      labels:
        - docs
    - title: Refactors
      labels:
        - refactor
    - title: Tests
      labels:
        - test
    - title: Build & CI
      labels:
        - build
        - ci
    - title: Chores
      labels:
        - chore
        - '*'
